# Generated by Django 4.2.20 on 2025-03-20 23:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("jobs", "0002_alter_job_company_alter_job_salary"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="employer",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jobs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
