name: Django CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  source:
    name: Source Stage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

  build:
    name: Build & Install
    runs-on: ubuntu-latest
    needs: source
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint pylint-django bandit pytest pytest-django pytest-cov

      - name: Set Environment Variables
        run: |
          echo "DJANGO_SETTINGS_MODULE=job_portal.settings" >> $GITHUB_ENV
          echo "AWS_DEFAULT_REGION=us-east-1" >> $GITHUB_ENV

  pylint:
    name: Static Code Analysis (Pylint)
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Pylint
        run: |
          pip install -r requirements.txt
          pip install pylint pylint-django

      - name: Run Pylint
        run: |
          pylint --rcfile=.pylintrc users/ jobs/ --fail-under=8.0
        continue-on-error: false

  pytest:
    name: Run Tests (Pytest)
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Pytest
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-django pytest-cov django

      - name: Run Pytest
        run: |
          pytest --cov=jobs --cov=users
        continue-on-error: false

  bandit:
    name: Security Analysis (Bandit)
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Bandit
        run: |
          pip install -r requirements.txt
          pip install bandit

      - name: Run Bandit
        run: |
          bandit -c .bandit.yml -r jobs/ users/
        continue-on-error: false

  deploy:
    name: Deploy to AWS Elastic Beanstalk
    runs-on: ubuntu-latest
    needs: [pytest, pylint, bandit]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install EB CLI
        run: pip install awsebcli

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to Elastic Beanstalk
        run: |
          eb init -p python-3.11 ${{ secrets.APP_NAME }} --region ${{ secrets.AWS_REGION }}
          eb use ${{ secrets.ENV_NAME }}
          eb deploy

      - name: Check Elastic Beanstalk Environment Status
        run: eb status
