name: Django CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  source:
    name: Source Stage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

  build:
    name: Build & Install
    runs-on: ubuntu-latest
    needs: source
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Create and Activate Virtual Environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint pylint-django bandit pytest pytest-django pytest-cov

  lint:
    name: Linting (Pylint)
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Pylint
        run: |
          pip install -r requirements.txt
          pip install pylint pylint-django django

      - name: Run Pylint
        run: |
          pylint --rcfile=.pylintrc users/ jobs/ --fail-under=8.0
        continue-on-error: false

  test:
    name: Run Tests (Pytest)
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Pytest and dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-django pytest-cov django

      - name: Run Pytest
        run: |
          pytest --cov=users --cov=jobs
        continue-on-error: false

  security:
    name: Security Check (Bandit)
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Bandit
        run: |
          pip install -r requirements.txt
          pip install bandit

      - name: Run Bandit
        run: |
          bandit -c .bandit.yml -r users/ jobs/
        continue-on-error: false

  deploy:
    name: Deploy to AWS Elastic Beanstalk
    runs-on: ubuntu-latest
    needs: [test, lint, security]  # Only deploy if all checks pass
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install EB CLI
        run: |
          pip install awsebcli

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to Elastic Beanstalk
        run: |
          eb init -p python-3.11 ${{ secrets.APP_NAME }} --region ${{ secrets.AWS_REGION }}
          eb use ${{ secrets.ENV_NAME }}
          eb deploy
