name: Django CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  source:
    name: Source Stage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
  build:
    name: Build and Test Stage
    runs-on: ubuntu-latest
    needs: source

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Create and Activate Virtual Environment
        run: |
          python3.9 -m venv env
          source env/bin/activate

      - name: Install dependencies
        run: |
          source env/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint
          pip install pylint-django pytest-django pytest bandit pytest-cov

      - name: Run Django Tests
        run: |
          source env/bin/activate
          pytest --cov=jobs --cov=accounts

      - name: Run Static Code Analysis (pylint)
        run: |
          source env/bin/activate
          pip install pylint
          pylint --rcfile=.pylintrc --disable=R,C users/ jobs/ --fail-under=8.0
          
      - name: Run Security Analysis (bandit)
        run: |
          source env/bin/activate
          pip install bandit
          bandit jobs/ users/

    #   - name: Deploy to AWS Elastic Beanstalk
    #     env:
    #       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #       AWS_REGION: "us-east-1"  # Change this to your AWS region
    #       EB_ENVIRONMENT: "job-portal-env"
    #       EB_APPLICATION: "JobPortalApp"
        # run: |
        #   pip install awsebcli
        #   eb init $EB_APPLICATION --platform "Python 3.9" --region $AWS_REGION
        #   eb deploy $EB_ENVIRONMENT
