name: Django CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  source:
    name: Source Stage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
  build:
    name: Build Stage
    runs-on: ubuntu-latest
    needs: source

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Create and Activate Virtual Environment
        run: |
          python3.9 -m venv env
          source env/bin/activate

      - name: Install Dependencies
        run: |
          source env/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint pylint-django pytest pytest-django bandit pytest-cov
          
      - name: Set Environment Variables
        run: |
          echo "DJANGO_SETTINGS_MODULE=job_portal.settings" >> $GITHUB_ENV
          echo "AWS_DEFAULT_REGION=us-east-1" >> $GITHUB_ENV

  pylint:
    name: Static Code Analysis (Pylint)
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python3.9 -m venv env
          source env/bin/activate
          pip install pylint pylint-django

      - name: Run Pylint
        run: |
          source env/bin/activate
          pylint users/ jobs/ --fail-under=8.0

  pytest:
    name: Test Stage (Pytest)
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python3.9 -m venv env
          source env/bin/activate
          pip install pytest pytest-django pytest-cov

      - name: Run Pytest
        run: |
          source env/bin/activate
          pytest --cov=jobs --cov=users

  bandit:
    name: Security Analysis (Bandit)
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python3.9 -m venv env
          source env/bin/activate
          pip install bandit

      - name: Run Bandit Security Analysis
        run: |
          source env/bin/activate
          bandit -r jobs/ users/
