name: Django CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  source:
    name: Source Stage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
  build:
    name: Build and Test Stage
    runs-on: ubuntu-latest
    needs: source

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Create and Activate Virtual Environment
        run: |
          python3.9 -m venv env
          source env/bin/activate

      - name: Install dependencies
        run: |
          source env/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint
          pip install pylint-django pytest-django pytest bandit pytest-cov
          
      - name: Set Environment Variables
        run: |
          source env/bin/activate
          echo "DJANGO_SETTINGS_MODULE=job_portal.settings" >> $GITHUB_ENV
          echo "AWS_DEFAULT_REGION=us-east-1" >> $GITHUB_ENV

      - name: Run Django Tests
        run: |
          source env/bin/activate
          pytest --cov=jobs --cov=users

      - name: Run Static Code Analysis (pylint)
        run: |
          source env/bin/activate
          pip install pylint
          pylint --rcfile=.pylintrc --disable=R,C users/ jobs/ --fail-under=8.0
          
      - name: Run Security Analysis (bandit)
        run: |
          source env/bin/activate
          pip install bandit
          bandit jobs/ users/

